package github

import (
	"bytes"
	"encoding/json"
	"fmt"
	"net/http"
	"os"
	"strings"
	"time"
)

type TestResult struct {
	ServiceName string
	Status      string // "pass" or "fail"
	RPS         float64
	AvgLatency  float64
	P95Latency  float64
	P99Latency  float64
	ErrorRate   float64
	TotalReqs   int
	DurationMs  float64
	Assertions  []AssertionResult
}

type AssertionResult struct {
	Metric   string
	Operator string
	Value    float64
	Actual   float64
	Passed   bool
}

// PostPRComment posts a formatted comment to a GitHub PR.
// It reads GITHUB_TOKEN, GITHUB_REPOSITORY, and PR number from environment.
func PostPRComment(result TestResult) error {
	token := os.Getenv("GITHUB_TOKEN")
	repo := os.Getenv("GITHUB_REPOSITORY") // "owner/repo"

	// Get PR number from GLOAD_PR_NUMBER or GITHUB_REF (refs/pull/123/merge)
	prNumber := os.Getenv("GLOAD_PR_NUMBER")
	if prNumber == "" {
		ref := os.Getenv("GITHUB_REF")
		// refs/pull/123/merge
		parts := strings.Split(ref, "/")
		if len(parts) >= 3 && parts[1] == "pull" {
			prNumber = parts[2]
		}
	}

	if token == "" || repo == "" || prNumber == "" {
		return fmt.Errorf("missing GITHUB_TOKEN, GITHUB_REPOSITORY, or PR number")
	}

	comment := FormatComment(result)

	url := fmt.Sprintf("https://api.github.com/repos/%s/issues/%s/comments", repo, prNumber)

	body, _ := json.Marshal(map[string]string{"body": comment})
	req, err := http.NewRequest("POST", url, bytes.NewReader(body))
	if err != nil {
		return err
	}

	req.Header.Set("Authorization", "Bearer "+token)
	req.Header.Set("Accept", "application/vnd.github+json")
	req.Header.Set("Content-Type", "application/json")
	req.Header.Set("X-GitHub-Api-Version", "2022-11-28")

	client := &http.Client{Timeout: 15 * time.Second}
	resp, err := client.Do(req)
	if err != nil {
		return err
	}
	defer resp.Body.Close()

	if resp.StatusCode >= 400 {
		return fmt.Errorf("GitHub API returned %d", resp.StatusCode)
	}
	return nil
}

// FormatComment creates a markdown comment for the PR.
func FormatComment(r TestResult) string {
	statusEmoji := "&#x2705;" // green check
	statusLabel := "PASSED"
	if r.Status == "fail" {
		statusEmoji = "&#x274c;" // red X
		statusLabel = "FAILED"
	}

	var sb strings.Builder
	sb.WriteString(fmt.Sprintf("## %s gload: **%s** — %s\n\n", statusEmoji, r.ServiceName, statusLabel))
	sb.WriteString("| Metric | Value |\n")
	sb.WriteString("|--------|-------|\n")
	sb.WriteString(fmt.Sprintf("| **RPS** | %.1f /s |\n", r.RPS))
	sb.WriteString(fmt.Sprintf("| **Avg Latency** | %.1fms |\n", r.AvgLatency))
	sb.WriteString(fmt.Sprintf("| **P95 Latency** | %.1fms |\n", r.P95Latency))
	sb.WriteString(fmt.Sprintf("| **P99 Latency** | %.1fms |\n", r.P99Latency))
	sb.WriteString(fmt.Sprintf("| **Error Rate** | %.1f%% |\n", r.ErrorRate))
	sb.WriteString(fmt.Sprintf("| **Total Requests** | %d |\n", r.TotalReqs))
	sb.WriteString(fmt.Sprintf("| **Duration** | %.1fs |\n", r.DurationMs/1000))

	if len(r.Assertions) > 0 {
		sb.WriteString("\n### Assertions\n\n")
		sb.WriteString("| Check | Expected | Actual | Result |\n")
		sb.WriteString("|-------|----------|--------|--------|\n")
		for _, a := range r.Assertions {
			icon := "&#x2705;"
			if !a.Passed {
				icon = "&#x274c;"
			}
			sb.WriteString(fmt.Sprintf("| %s %s %s | %v | %.1f | %s |\n",
				a.Metric, a.Operator, formatValue(a.Value, a.Metric),
				formatValue(a.Value, a.Metric), a.Actual, icon))
		}
	}

	sb.WriteString(fmt.Sprintf("\n<sub>Generated by gload at %s</sub>\n", time.Now().UTC().Format("2006-01-02 15:04 UTC")))
	return sb.String()
}

func formatValue(v float64, metric string) string {
	switch {
	case strings.Contains(metric, "latency"):
		return fmt.Sprintf("%.1fms", v)
	case metric == "error_rate":
		return fmt.Sprintf("%.1f%%", v)
	default:
		return fmt.Sprintf("%.1f", v)
	}
}
