package notifier

import (
	"fmt"
	"net/smtp"
	"strings"
)

// EmailConfig holds SMTP configuration for sending email notifications.
type EmailConfig struct {
	SMTPHost string // e.g. "smtp.gmail.com"
	SMTPPort string // e.g. "587"
	Username string
	Password string
	From     string
	To       []string // recipient emails
}

// SendEmail sends a test result notification via SMTP.
func SendEmail(cfg EmailConfig, result TestResult) error {
	if cfg.SMTPHost == "" || len(cfg.To) == 0 {
		return nil
	}

	statusEmoji := "PASSED"
	if result.Status == "fail" {
		statusEmoji = "FAILED"
	}

	subject := fmt.Sprintf("gload: %s — %s", result.ServiceName, statusEmoji)

	body := fmt.Sprintf(`Load test completed for %s

Status: %s
URL: %s

Results:
  RPS: %.1f
  Avg Latency: %.1fms
  P95 Latency: %.1fms
  Error Rate: %.1f%%
  Total Requests: %d
  Duration: %.1fs

--
Generated by gload`,
		result.ServiceName, strings.ToUpper(result.Status), result.ServiceURL,
		result.RPS, result.AvgLatency, result.P95Latency, result.ErrorRate,
		result.TotalReqs, result.Duration/1000)

	msg := fmt.Sprintf("From: %s\r\nTo: %s\r\nSubject: %s\r\nContent-Type: text/plain; charset=UTF-8\r\n\r\n%s",
		cfg.From, strings.Join(cfg.To, ","), subject, body)

	auth := smtp.PlainAuth("", cfg.Username, cfg.Password, cfg.SMTPHost)
	addr := cfg.SMTPHost + ":" + cfg.SMTPPort

	return smtp.SendMail(addr, auth, cfg.From, cfg.To, []byte(msg))
}
